// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WOVQPOOQ_QPOOOOQO'#Cb'#CbOVQPO'#CbOVQPO,58|OVQPO,58|OmQPO,58|OOQO1G.h1G.hO!OQPO1G.h",
  stateData: "!d~OPOS~ORQOZRO~OVSOWSOXTOYTO~OVSOWSOXTOYTO[VO~OVSOWSOSUiXUiYUi[Ui~O",
  goto: "dVPPPPPPWQPOQURQVSRWT",
  nodeNames: "⚠ NEWLINE prog INT",
  maxTerm: 12,
  skippedNodes: [0,1],
  repeatNodeCount: 0,
  tokenData: "!q~RXYZn]^nxyyyz!Oz{!T{|!Y}!O!_!P!Q!d!Q![!i~sQP~YZn]^n~!OOZ~~!TO[~~!YOV~~!_OX~~!dOY~~!iOW~~!nPR~!Q![!i",
  tokenizers: [0],
  topRules: {"prog":[0,2]},
  tokenPrec: 0
})
