// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QQVQPOOO_QQO'#C_OOQO'#Ca'#CaQVQPOOOOQO'#C`'#C`OdQPO,58yOOQO-E6_-E6_OOQO1G.e1G.e",
  stateData: "i~OWOS~OQQOXPO~OYSO~OZVO~O",
  goto: "dUPPPVZ^TQORRTPQRORUR",
  nodeNames: "⚠ Document Word ParensWord WordInParens",
  maxTerm: 11,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!R~RVXYhYZh]^hpqhxymyzr#T#ow~mOW~~rOX~~wOZ~R!OPQPYQ#T#ow",
  tokenizers: [0, 1],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
